//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdeudosInstalaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdeudosInstalaciones()
        {
            this.MonitoreoIngresos = new HashSet<MonitoreoIngresos>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid IdProveedor { get; set; }
        public Nullable<System.Guid> IdComprobante { get; set; }
        public System.Guid IdCliente { get; set; }
        public Nullable<System.DateTime> FechaContrato { get; set; }
        public Nullable<bool> PagoComision { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<System.Guid> IdAcessor { get; set; }
        public Nullable<System.Guid> IdPaquete { get; set; }
        public Nullable<System.Guid> IdMensualidad { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Concepto { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public double Total { get; set; }
        public Nullable<System.DateTime> FechaInstalacion { get; set; }
        public Nullable<System.Guid> IdInstalador { get; set; }
        public string Comentarios { get; set; }
        public Nullable<double> Anticipo { get; set; }
        public bool Pagado { get; set; }
        public bool Instalacion { get; set; }
        public Nullable<bool> RequiereFacturacion { get; set; }
        public Nullable<bool> RequiereCancelacion { get; set; }
        public Nullable<bool> RevisoRobot { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string ClaveProdServ { get; set; }
    
        public virtual PAC PAC { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Empleados Empleados1 { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoreoIngresos> MonitoreoIngresos { get; set; }
    }
}
