//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFDIPorOperacion
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdNominaHistorial { get; set; }
        public Nullable<System.Guid> IdAdeudosInstalaciones { get; set; }
        public Nullable<System.Guid> IdCFDI { get; set; }
    }
}
