//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.NominaHistorial = new HashSet<NominaHistorial>();
            this.AdeudosInstalaciones = new HashSet<AdeudosInstalaciones>();
            this.AdeudosInstalaciones1 = new HashSet<AdeudosInstalaciones>();
        }
    
        public System.Guid Id { get; set; }
        public int NoEmpleado { get; set; }
        public Nullable<System.Guid> IdProveedor { get; set; }
        public string Nombre { get; set; }
        public string ApellidoMaterno { get; set; }
        public string ApellidoPaterno { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaInicioRelLaboral { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public byte[] HuellaDactilar { get; set; }
        public byte[] Foto { get; set; }
        public string INE { get; set; }
        public string NumeroSeguridadSocial { get; set; }
        public string Departamento { get; set; }
        public string Direccion { get; set; }
        public string Puesto { get; set; }
        public string RiesgoPuesto { get; set; }
        public string TipoContrato { get; set; }
        public string TipoJornada { get; set; }
        public Nullable<double> SalarioDiario { get; set; }
        public string Banco { get; set; }
        public string CuentaBancaria { get; set; }
        public string ClaveEntFed { get; set; }
        public string GradoEstudios { get; set; }
        public string Telefono { get; set; }
        public string TelefonoEmergencia { get; set; }
        public byte[] Firma { get; set; }
        public string TipoSangre { get; set; }
        public string CUIP { get; set; }
        public string NumeroDeLicencia { get; set; }
        public string NumeroDeAutorizacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual PAC PAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaHistorial> NominaHistorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdeudosInstalaciones> AdeudosInstalaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdeudosInstalaciones> AdeudosInstalaciones1 { get; set; }
    }
}
