//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaPercepciones
    {
        public System.Guid Id { get; set; }
        public System.Guid IdNominaHistorial { get; set; }
        public string Tipo { get; set; }
        public string Clave { get; set; }
        public string Concepto { get; set; }
        public Nullable<double> ImporteExcento { get; set; }
        public Nullable<double> ImporteGravado { get; set; }
        public Nullable<System.Guid> HorasExtras { get; set; }
        public Nullable<double> ValorMercado { get; set; }
        public Nullable<double> PrecioOrtorgarse { get; set; }
    
        public virtual NominaHistorial NominaHistorial { get; set; }
        public virtual NominaHorasExtras NominaHorasExtras { get; set; }
    }
}
