//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAC()
        {
            this.CFDI = new HashSet<CFDI>();
            this.Clientes = new HashSet<Clientes>();
            this.Empleados = new HashSet<Empleados>();
            this.NominaHistorial = new HashSet<NominaHistorial>();
            this.AdeudosInstalaciones = new HashSet<AdeudosInstalaciones>();
        }
    
        public System.Guid Id { get; set; }
        public string RFC { get; set; }
        public string Usuario { get; set; }
        public byte[] Contrasena { get; set; }
        public string Nombre { get; set; }
        public string CURP { get; set; }
        public Nullable<bool> PersonaMoral { get; set; }
        public byte[] Llave { get; set; }
        public byte[] Certificado { get; set; }
        public byte[] ContrasenaLlave { get; set; }
        public string RegimenFiscal { get; set; }
        public string RegistroPatronal { get; set; }
        public string RfcPatronOrigen { get; set; }
        public byte[] Logo { get; set; }
        public string LugarExpedicion { get; set; }
        public Nullable<System.DateTime> FechaVigenciaIncio { get; set; }
        public Nullable<System.DateTime> FechaVigenciaFinal { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFDI> CFDI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaHistorial> NominaHistorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdeudosInstalaciones> AdeudosInstalaciones { get; set; }
    }
}
