//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdeudosInstalaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdeudosInstalaciones()
        {
            this.CFDIPorOperacion = new HashSet<CFDIPorOperacion>();
            this.MonitoreoIngresos = new HashSet<MonitoreoIngresos>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid IdProveedor { get; set; }
        public System.Guid IdCliente { get; set; }
        public Nullable<System.Guid> IdPaquete { get; set; }
        public string c_FormaPago { get; set; }
        public string c_MetodoPago { get; set; }
        public string c_UsoCFDI { get; set; }
        public string c_Moneda { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public double Total { get; set; }
        public Nullable<System.DateTime> FechaInstalacion { get; set; }
        public string Comentarios { get; set; }
        public bool Pagado { get; set; }
        public Nullable<bool> RequiereFacturacion { get; set; }
        public Nullable<bool> RequiereCorreo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
    
        public virtual FormaDePago FormaDePago { get; set; }
        public virtual MetodosDePago MetodosDePago { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual PAC PAC { get; set; }
        public virtual UsoCFDI UsoCFDI { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFDIPorOperacion> CFDIPorOperacion { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoreoIngresos> MonitoreoIngresos { get; set; }
    }
}
