//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociados
    {
        public System.Guid IdAsociado { get; set; }
        public System.Guid IdCliente { get; set; }
        public int Puntos { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public bool Pago { get; set; }
    }
}
