//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociados
    {
        public System.Guid IdAsociado { get; set; }
        public System.Guid IdCliente { get; set; }
        public int Puntos { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public bool Pago { get; set; }
    }
}
