//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFDIPorOperacion
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdNominaHistorial { get; set; }
        public Nullable<System.Guid> IdAdeudosInstalaciones { get; set; }
        public Nullable<System.Guid> IdCFDI { get; set; }
    }
}
