//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaveProdServ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClaveProdServ()
        {
            this.ClaveProdServHistorial = new HashSet<ClaveProdServHistorial>();
            this.MonitoreoIngresos = new HashSet<MonitoreoIngresos>();
        }
    
        public string c_ClaveProdServ { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string Division { get; set; }
        public string Grupo { get; set; }
        public string Clase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaveProdServHistorial> ClaveProdServHistorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoreoIngresos> MonitoreoIngresos { get; set; }
    }
}
