//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteComponentes
    {
        public System.Guid IdClienteComponente { get; set; }
        public System.Guid IdCliente { get; set; }
        public System.Guid IdComponente { get; set; }
        public System.Guid IdComponenteArduino { get; set; }
    }
}
