//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigosPostales
    {
        public string CodigoPostal { get; set; }
        public string c_Estados { get; set; }
        public string Municipio { get; set; }
        public string Localidad { get; set; }
    
        public virtual Estados Estados { get; set; }
    }
}
