//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componentes
    {
        public System.Guid IdComponente { get; set; }
        public string Nombre { get; set; }
        public int Costo { get; set; }
        public bool EsComponenteArduino { get; set; }
        public Nullable<System.DateTime> FechaInstalacion { get; set; }
        public Nullable<System.DateTime> FechaMantenimiento { get; set; }
        public string UsuarioInstalo { get; set; }
        public string UsuarioMantenimiento { get; set; }
    }
}
