//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraInventario
    {
        public System.Guid IdCompraInventario { get; set; }
        public Nullable<System.Guid> IdCompra { get; set; }
        public Nullable<System.Guid> IdDispositivo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Monto { get; set; }
    }
}
