//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correos
    {
        public System.Guid IdCorreo { get; set; }
        public string Email { get; set; }
        public System.DateTime Fecha { get; set; }
        public string TipoMensaje { get; set; }
        public Nullable<int> Folio { get; set; }
    }
}
