//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioOperaciones
    {
        public System.Guid Id { get; set; }
        public System.Guid IdCliente { get; set; }
        public Nullable<System.TimeSpan> DomingoInicio { get; set; }
        public Nullable<System.TimeSpan> DomingoFinal { get; set; }
        public Nullable<System.TimeSpan> LunesInicio { get; set; }
        public Nullable<System.TimeSpan> LunesFinal { get; set; }
        public Nullable<System.TimeSpan> MartesInicio { get; set; }
        public Nullable<System.TimeSpan> MartesFinal { get; set; }
        public Nullable<System.TimeSpan> MiercolesInicio { get; set; }
        public Nullable<System.TimeSpan> MiercolesFinal { get; set; }
        public Nullable<System.TimeSpan> JuevesInicio { get; set; }
        public Nullable<System.TimeSpan> JuevesFinal { get; set; }
        public Nullable<System.TimeSpan> ViernesInicio { get; set; }
        public Nullable<System.TimeSpan> ViernesFinal { get; set; }
        public Nullable<System.TimeSpan> SabadoInicio { get; set; }
        public Nullable<System.TimeSpan> SabadoFinal { get; set; }
        public bool Active { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.Guid UsuarioCreacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
