//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Llamadas
    {
        public System.Guid IdLlamada { get; set; }
        public int IdSkypeLlamada { get; set; }
        public string Llamada { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
