//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public System.Guid IdUsurioEmisor { get; set; }
        public System.Guid IdUsurioRepcetor { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
