//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaHorasExtras
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdPercepcion { get; set; }
        public double Dias { get; set; }
        public string Tipos { get; set; }
        public double HorasExtras { get; set; }
        public double ImportePagado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
    
        public virtual Horas Horas { get; set; }
        public virtual NominaPercepcion NominaPercepcion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
