//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaJubilacionPensionRetiro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NominaJubilacionPensionRetiro()
        {
            this.NominaPercepciones = new HashSet<NominaPercepciones>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<double> TotalUnaExhibicion { get; set; }
        public Nullable<double> TotalParcialidad { get; set; }
        public Nullable<double> MontoDiario { get; set; }
        public double IngresoAcumulable { get; set; }
        public double IngresoNoAcumulable { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaPercepciones> NominaPercepciones { get; set; }
    }
}
