//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaHistorial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NominaHistorial()
        {
            this.MonitoreoIngresos = new HashSet<MonitoreoIngresos>();
            this.NominaDeduccion = new HashSet<NominaDeduccion>();
            this.NominaIncapacidad = new HashSet<NominaIncapacidad>();
            this.NominaOtrosPago = new HashSet<NominaOtrosPago>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid IdProveedor { get; set; }
        public System.Guid IdEmpleado { get; set; }
        public string TipoNomina { get; set; }
        public System.DateTime FechaPago { get; set; }
        public System.DateTime FechaInicialPago { get; set; }
        public System.DateTime FechaFinalPago { get; set; }
        public double NumeroDiasPagados { get; set; }
        public string TipoRegimen { get; set; }
        public string Moneda { get; set; }
        public string PeriodicidadPago { get; set; }
        public string LugarExpedicion { get; set; }
        public Nullable<System.Guid> IdPercepciones { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    
        public virtual Nominas Nominas { get; set; }
        public virtual PAC PAC { get; set; }
        public virtual PeriodicidadPagos PeriodicidadPagos { get; set; }
        public virtual Regimen Regimen { get; set; }
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoreoIngresos> MonitoreoIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaDeduccion> NominaDeduccion { get; set; }
        public virtual NominaPercepciones NominaPercepciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaIncapacidad> NominaIncapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaOtrosPago> NominaOtrosPago { get; set; }
    }
}
