//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaJubilacionPensionRetiro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NominaJubilacionPensionRetiro()
        {
            this.NominaPercepciones = new HashSet<NominaPercepciones>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<double> TotalUnaExhibicion { get; set; }
        public Nullable<double> TotalParcialidad { get; set; }
        public Nullable<double> MontoDiario { get; set; }
        public double IngresoAcumulable { get; set; }
        public double IngresoNoAcumulable { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaPercepciones> NominaPercepciones { get; set; }
    }
}
