//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public System.Guid IdPago { get; set; }
        public System.Guid IdCompra { get; set; }
        public System.Guid IdCliente { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public bool Pagado { get; set; }
    }
}
