//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquetes
    {
        public System.Guid Id { get; set; }
        public System.Guid IdAdeudo { get; set; }
        public Nullable<System.Guid> IdInventario { get; set; }
        public Nullable<double> Precio { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Inventario Inventario { get; set; }
    }
}
