//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsudioAlEmpleo
    {
        public System.Guid Id { get; set; }
        public double LimiteInferior { get; set; }
        public double LimiteSuperior { get; set; }
        public double SubsidioEmpleo { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
