//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoreo_360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsudioAlEmpleo
    {
        public System.Guid Id { get; set; }
        public double LimiteInferior { get; set; }
        public double LimiteSuperior { get; set; }
        public double SubsidioEmpleo { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
