//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdeudosForPanel
    {
        public System.Guid Id { get; set; }
        public string Cliente { get; set; }
        public string Empresa { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public string Concepto { get; set; }
        public bool Pagado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.Guid> IdCFDI { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
    }
}
