//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFDI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFDI()
        {
            this.CFDIEnDeuda = new HashSet<CFDIEnDeuda>();
        }
    
        public System.Guid Id { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Folio { get; set; }
        public byte[] XML { get; set; }
        public string Ruta { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public Nullable<System.Guid> IdEmpleado { get; set; }
        public System.Guid IdProveedor { get; set; }
        public bool Cancelado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
    
        public virtual PAC PAC { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFDIEnDeuda> CFDIEnDeuda { get; set; }
    }
}
