//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaveProdServPorPAC
    {
        public System.Guid Id { get; set; }
        public System.Guid IdPAC { get; set; }
        public string Clase { get; set; }
        public System.Guid UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual PAC PAC { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
