//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosForPanel
    {
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public string RFC { get; set; }
        public string Foto { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public System.Guid UsuarioCreacion { get; set; }
    }
}
