//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.AdeudosInstalaciones = new HashSet<AdeudosInstalaciones>();
            this.AdeudosInstalaciones1 = new HashSet<AdeudosInstalaciones>();
            this.CFDI = new HashSet<CFDI>();
            this.NominaHistorial = new HashSet<NominaHistorial>();
        }
    
        public System.Guid Id { get; set; }
        public int NoEmpleado { get; set; }
        public Nullable<System.Guid> IdProveedor { get; set; }
        public string Nombre { get; set; }
        public string ApellidoMaterno { get; set; }
        public string ApellidoPaterno { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaInicioRelLaboral { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public byte[] HuellaDactilar { get; set; }
        public string Foto { get; set; }
        public string INE { get; set; }
        public string NumeroSeguridadSocial { get; set; }
        public string Departamento { get; set; }
        public string Direccion { get; set; }
        public string Puesto { get; set; }
        public string RiesgoPuesto { get; set; }
        public string TipoContrato { get; set; }
        public string TipoJornada { get; set; }
        public Nullable<double> SalarioDiario { get; set; }
        public string Banco { get; set; }
        public string CuentaBancaria { get; set; }
        public string ClaveEntFed { get; set; }
        public string GradoEstudios { get; set; }
        public string Telefono { get; set; }
        public string TelefonoEmergencia { get; set; }
        public byte[] Firma { get; set; }
        public string TipoSangre { get; set; }
        public string CUIP { get; set; }
        public string NumeroDeLicencia { get; set; }
        public string NumeroDeAutorizacion { get; set; }
        public Nullable<System.Guid> IdPlantilla { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.Guid UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Contratos Contratos { get; set; }
        public virtual Jornadas Jornadas { get; set; }
        public virtual PAC PAC { get; set; }
        public virtual RiesgoPuesto RiesgoPuesto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdeudosInstalaciones> AdeudosInstalaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdeudosInstalaciones> AdeudosInstalaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFDI> CFDI { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaHistorial> NominaHistorial { get; set; }
    }
}
