//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Llamadas
    {
        public System.Guid IdLlamada { get; set; }
        public int IdSkypeLlamada { get; set; }
        public string Llamada { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
