//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitoreoIngresos
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdAdeudo { get; set; }
        public Nullable<System.Guid> IdNominaHistorial { get; set; }
        public Nullable<double> Cargos { get; set; }
        public Nullable<double> Abonos { get; set; }
        public Nullable<double> CargosUSD { get; set; }
        public Nullable<double> AbonosUSD { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public string FormaDePago { get; set; }
        public string MetodoDePago { get; set; }
        public string UsoCFDI { get; set; }
        public string Moneda { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.Guid UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual FormaDePago FormaDePago1 { get; set; }
        public virtual MetodosDePago MetodosDePago { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual UsoCFDI UsoCFDI1 { get; set; }
        public virtual AdeudosInstalaciones AdeudosInstalaciones { get; set; }
        public virtual NominaHistorial NominaHistorial { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
