//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaHorasExtras
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdPercepcion { get; set; }
        public double Dias { get; set; }
        public string Tipos { get; set; }
        public double HorasExtras { get; set; }
        public double ImportePagado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
    
        public virtual Horas Horas { get; set; }
        public virtual NominaPercepcion NominaPercepcion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
