//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAC()
        {
            this.AdeudosInstalaciones = new HashSet<AdeudosInstalaciones>();
            this.CFDI = new HashSet<CFDI>();
            this.CFDIEnDeuda = new HashSet<CFDIEnDeuda>();
            this.ClaveProdServHistorial = new HashSet<ClaveProdServHistorial>();
            this.ClaveProdServPorPAC = new HashSet<ClaveProdServPorPAC>();
            this.Clientes = new HashSet<Clientes>();
            this.Empleados = new HashSet<Empleados>();
            this.NominaHistorial = new HashSet<NominaHistorial>();
        }
    
        public System.Guid Id { get; set; }
        public string RFC { get; set; }
        public string Usuario { get; set; }
        public byte[] Contrasena { get; set; }
        public string Nombre { get; set; }
        public string CURP { get; set; }
        public Nullable<bool> PersonaMoral { get; set; }
        public byte[] Llave { get; set; }
        public byte[] Certificado { get; set; }
        public byte[] ContrasenaLlave { get; set; }
        public string RegimenFiscal { get; set; }
        public string RegistroPatronal { get; set; }
        public string RfcPatronOrigen { get; set; }
        public string Logo { get; set; }
        public string LugarExpedicion { get; set; }
        public Nullable<System.DateTime> FechaVigenciaIncio { get; set; }
        public Nullable<System.DateTime> FechaVigenciaFinal { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdeudosInstalaciones> AdeudosInstalaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFDI> CFDI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFDIEnDeuda> CFDIEnDeuda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaveProdServHistorial> ClaveProdServHistorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaveProdServPorPAC> ClaveProdServPorPAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaHistorial> NominaHistorial { get; set; }
    }
}
