//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACForPanel
    {
        public System.Guid Id { get; set; }
        public string RFC { get; set; }
        public string Nombre { get; set; }
        public string CURP { get; set; }
        public string Logo { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
        public bool Activo { get; set; }
        public string RegimenFiscal { get; set; }
    }
}
