//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.WsEnrola {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUsuario", Namespace="http://tempuri.org/")]
    public enum TipoUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClienteConAcceso = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cliente = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSEnrolaResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WSEnrolaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeDeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MensajeDeError {
            get {
                return this.MensajeDeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeDeErrorField, value) != true)) {
                    this.MensajeDeErrorField = value;
                    this.RaisePropertyChanged("MensajeDeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsEnrola.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name RfcAdmin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarUsuario", ReplyAction="*")]
        Dashboard.WsEnrola.AgregarUsuarioResponse AgregarUsuario(Dashboard.WsEnrola.AgregarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.AgregarUsuarioResponse> AgregarUsuarioAsync(Dashboard.WsEnrola.AgregarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name RfcAdmin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AsignarTimbres", ReplyAction="*")]
        Dashboard.WsEnrola.AsignarTimbresResponse AsignarTimbres(Dashboard.WsEnrola.AsignarTimbresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AsignarTimbres", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.AsignarTimbresResponse> AsignarTimbresAsync(Dashboard.WsEnrola.AsignarTimbresRequest request);
        
        // CODEGEN: Generating message contract since element name RfcAdmin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarTimbres", ReplyAction="*")]
        Dashboard.WsEnrola.AgregarTimbresResponse AgregarTimbres(Dashboard.WsEnrola.AgregarTimbresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarTimbres", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.AgregarTimbresResponse> AgregarTimbresAsync(Dashboard.WsEnrola.AgregarTimbresRequest request);
        
        // CODEGEN: Generating message contract since element name RfcAdmin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuitarTimbres", ReplyAction="*")]
        Dashboard.WsEnrola.QuitarTimbresResponse QuitarTimbres(Dashboard.WsEnrola.QuitarTimbresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuitarTimbres", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.QuitarTimbresResponse> QuitarTimbresAsync(Dashboard.WsEnrola.QuitarTimbresRequest request);
        
        // CODEGEN: Generating message contract since element name RfcUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiarClave", ReplyAction="*")]
        Dashboard.WsEnrola.CambiarClaveResponse CambiarClave(Dashboard.WsEnrola.CambiarClaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiarClave", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.CambiarClaveResponse> CambiarClaveAsync(Dashboard.WsEnrola.CambiarClaveRequest request);
        
        // CODEGEN: Generating message contract since element name RfcAdmin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InhabilitarUsuario", ReplyAction="*")]
        Dashboard.WsEnrola.InhabilitarUsuarioResponse InhabilitarUsuario(Dashboard.WsEnrola.InhabilitarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InhabilitarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.InhabilitarUsuarioResponse> InhabilitarUsuarioAsync(Dashboard.WsEnrola.InhabilitarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name RfcAdmin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearUsuarioRV", ReplyAction="*")]
        Dashboard.WsEnrola.CrearUsuarioRVResponse CrearUsuarioRV(Dashboard.WsEnrola.CrearUsuarioRVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearUsuarioRV", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.CrearUsuarioRVResponse> CrearUsuarioRVAsync(Dashboard.WsEnrola.CrearUsuarioRVRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.AgregarUsuarioRequestBody Body;
        
        public AgregarUsuarioRequest() {
        }
        
        public AgregarUsuarioRequest(Dashboard.WsEnrola.AgregarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RfcAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CuentaAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClaveAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RfcUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CuentaUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ClaveUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RazonSocialUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CorreoUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public Dashboard.WsEnrola.TipoUsuario TipoUsuario;
        
        public AgregarUsuarioRequestBody() {
        }
        
        public AgregarUsuarioRequestBody(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, string ClaveUsuario, string RazonSocialUsuario, string CorreoUsuario, Dashboard.WsEnrola.TipoUsuario TipoUsuario) {
            this.RfcAdmin = RfcAdmin;
            this.CuentaAdmin = CuentaAdmin;
            this.ClaveAdmin = ClaveAdmin;
            this.RfcUsuario = RfcUsuario;
            this.CuentaUsuario = CuentaUsuario;
            this.ClaveUsuario = ClaveUsuario;
            this.RazonSocialUsuario = RazonSocialUsuario;
            this.CorreoUsuario = CorreoUsuario;
            this.TipoUsuario = TipoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.AgregarUsuarioResponseBody Body;
        
        public AgregarUsuarioResponse() {
        }
        
        public AgregarUsuarioResponse(Dashboard.WsEnrola.AgregarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WsEnrola.WSEnrolaResponse AgregarUsuarioResult;
        
        public AgregarUsuarioResponseBody() {
        }
        
        public AgregarUsuarioResponseBody(Dashboard.WsEnrola.WSEnrolaResponse AgregarUsuarioResult) {
            this.AgregarUsuarioResult = AgregarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsignarTimbresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsignarTimbres", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.AsignarTimbresRequestBody Body;
        
        public AsignarTimbresRequest() {
        }
        
        public AsignarTimbresRequest(Dashboard.WsEnrola.AsignarTimbresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AsignarTimbresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RfcAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UsuarioAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClaveAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RfcUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CuentaUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Timbres;
        
        public AsignarTimbresRequestBody() {
        }
        
        public AsignarTimbresRequestBody(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            this.RfcAdmin = RfcAdmin;
            this.UsuarioAdmin = UsuarioAdmin;
            this.ClaveAdmin = ClaveAdmin;
            this.RfcUsuario = RfcUsuario;
            this.CuentaUsuario = CuentaUsuario;
            this.Timbres = Timbres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsignarTimbresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsignarTimbresResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.AsignarTimbresResponseBody Body;
        
        public AsignarTimbresResponse() {
        }
        
        public AsignarTimbresResponse(Dashboard.WsEnrola.AsignarTimbresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AsignarTimbresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WsEnrola.WSEnrolaResponse AsignarTimbresResult;
        
        public AsignarTimbresResponseBody() {
        }
        
        public AsignarTimbresResponseBody(Dashboard.WsEnrola.WSEnrolaResponse AsignarTimbresResult) {
            this.AsignarTimbresResult = AsignarTimbresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarTimbresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarTimbres", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.AgregarTimbresRequestBody Body;
        
        public AgregarTimbresRequest() {
        }
        
        public AgregarTimbresRequest(Dashboard.WsEnrola.AgregarTimbresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarTimbresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RfcAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UsuarioAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClaveAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RfcUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CuentaUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Timbres;
        
        public AgregarTimbresRequestBody() {
        }
        
        public AgregarTimbresRequestBody(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            this.RfcAdmin = RfcAdmin;
            this.UsuarioAdmin = UsuarioAdmin;
            this.ClaveAdmin = ClaveAdmin;
            this.RfcUsuario = RfcUsuario;
            this.CuentaUsuario = CuentaUsuario;
            this.Timbres = Timbres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarTimbresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarTimbresResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.AgregarTimbresResponseBody Body;
        
        public AgregarTimbresResponse() {
        }
        
        public AgregarTimbresResponse(Dashboard.WsEnrola.AgregarTimbresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarTimbresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WsEnrola.WSEnrolaResponse AgregarTimbresResult;
        
        public AgregarTimbresResponseBody() {
        }
        
        public AgregarTimbresResponseBody(Dashboard.WsEnrola.WSEnrolaResponse AgregarTimbresResult) {
            this.AgregarTimbresResult = AgregarTimbresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuitarTimbresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuitarTimbres", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.QuitarTimbresRequestBody Body;
        
        public QuitarTimbresRequest() {
        }
        
        public QuitarTimbresRequest(Dashboard.WsEnrola.QuitarTimbresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuitarTimbresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RfcAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UsuarioAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClaveAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RfcUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CuentaUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Timbres;
        
        public QuitarTimbresRequestBody() {
        }
        
        public QuitarTimbresRequestBody(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            this.RfcAdmin = RfcAdmin;
            this.UsuarioAdmin = UsuarioAdmin;
            this.ClaveAdmin = ClaveAdmin;
            this.RfcUsuario = RfcUsuario;
            this.CuentaUsuario = CuentaUsuario;
            this.Timbres = Timbres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuitarTimbresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuitarTimbresResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.QuitarTimbresResponseBody Body;
        
        public QuitarTimbresResponse() {
        }
        
        public QuitarTimbresResponse(Dashboard.WsEnrola.QuitarTimbresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuitarTimbresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WsEnrola.WSEnrolaResponse QuitarTimbresResult;
        
        public QuitarTimbresResponseBody() {
        }
        
        public QuitarTimbresResponseBody(Dashboard.WsEnrola.WSEnrolaResponse QuitarTimbresResult) {
            this.QuitarTimbresResult = QuitarTimbresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarClaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarClave", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.CambiarClaveRequestBody Body;
        
        public CambiarClaveRequest() {
        }
        
        public CambiarClaveRequest(Dashboard.WsEnrola.CambiarClaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiarClaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RfcUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CuentaUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClaveActual;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ClaveNueva;
        
        public CambiarClaveRequestBody() {
        }
        
        public CambiarClaveRequestBody(string RfcUsuario, string CuentaUsuario, string ClaveActual, string ClaveNueva) {
            this.RfcUsuario = RfcUsuario;
            this.CuentaUsuario = CuentaUsuario;
            this.ClaveActual = ClaveActual;
            this.ClaveNueva = ClaveNueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarClaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarClaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.CambiarClaveResponseBody Body;
        
        public CambiarClaveResponse() {
        }
        
        public CambiarClaveResponse(Dashboard.WsEnrola.CambiarClaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiarClaveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WsEnrola.WSEnrolaResponse CambiarClaveResult;
        
        public CambiarClaveResponseBody() {
        }
        
        public CambiarClaveResponseBody(Dashboard.WsEnrola.WSEnrolaResponse CambiarClaveResult) {
            this.CambiarClaveResult = CambiarClaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InhabilitarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InhabilitarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.InhabilitarUsuarioRequestBody Body;
        
        public InhabilitarUsuarioRequest() {
        }
        
        public InhabilitarUsuarioRequest(Dashboard.WsEnrola.InhabilitarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InhabilitarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RfcAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CuentaAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClaveAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RfcUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CuentaUsuario;
        
        public InhabilitarUsuarioRequestBody() {
        }
        
        public InhabilitarUsuarioRequestBody(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario) {
            this.RfcAdmin = RfcAdmin;
            this.CuentaAdmin = CuentaAdmin;
            this.ClaveAdmin = ClaveAdmin;
            this.RfcUsuario = RfcUsuario;
            this.CuentaUsuario = CuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InhabilitarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InhabilitarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.InhabilitarUsuarioResponseBody Body;
        
        public InhabilitarUsuarioResponse() {
        }
        
        public InhabilitarUsuarioResponse(Dashboard.WsEnrola.InhabilitarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InhabilitarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WsEnrola.WSEnrolaResponse InhabilitarUsuarioResult;
        
        public InhabilitarUsuarioResponseBody() {
        }
        
        public InhabilitarUsuarioResponseBody(Dashboard.WsEnrola.WSEnrolaResponse InhabilitarUsuarioResult) {
            this.InhabilitarUsuarioResult = InhabilitarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearUsuarioRVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearUsuarioRV", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.CrearUsuarioRVRequestBody Body;
        
        public CrearUsuarioRVRequest() {
        }
        
        public CrearUsuarioRVRequest(Dashboard.WsEnrola.CrearUsuarioRVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearUsuarioRVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RfcAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CuentaAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClaveAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RfcUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CuentaUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ClaveUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CorreoUsuario;
        
        public CrearUsuarioRVRequestBody() {
        }
        
        public CrearUsuarioRVRequestBody(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, string ClaveUsuario, string CorreoUsuario) {
            this.RfcAdmin = RfcAdmin;
            this.CuentaAdmin = CuentaAdmin;
            this.ClaveAdmin = ClaveAdmin;
            this.RfcUsuario = RfcUsuario;
            this.CuentaUsuario = CuentaUsuario;
            this.ClaveUsuario = ClaveUsuario;
            this.CorreoUsuario = CorreoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearUsuarioRVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearUsuarioRVResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dashboard.WsEnrola.CrearUsuarioRVResponseBody Body;
        
        public CrearUsuarioRVResponse() {
        }
        
        public CrearUsuarioRVResponse(Dashboard.WsEnrola.CrearUsuarioRVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearUsuarioRVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WsEnrola.WSEnrolaResponse CrearUsuarioRVResult;
        
        public CrearUsuarioRVResponseBody() {
        }
        
        public CrearUsuarioRVResponseBody(Dashboard.WsEnrola.WSEnrolaResponse CrearUsuarioRVResult) {
            this.CrearUsuarioRVResult = CrearUsuarioRVResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Dashboard.WsEnrola.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Dashboard.WsEnrola.Service1Soap>, Dashboard.WsEnrola.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WsEnrola.AgregarUsuarioResponse Dashboard.WsEnrola.Service1Soap.AgregarUsuario(Dashboard.WsEnrola.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuario(request);
        }
        
        public Dashboard.WsEnrola.WSEnrolaResponse AgregarUsuario(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, string ClaveUsuario, string RazonSocialUsuario, string CorreoUsuario, Dashboard.WsEnrola.TipoUsuario TipoUsuario) {
            Dashboard.WsEnrola.AgregarUsuarioRequest inValue = new Dashboard.WsEnrola.AgregarUsuarioRequest();
            inValue.Body = new Dashboard.WsEnrola.AgregarUsuarioRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.CuentaAdmin = CuentaAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.RazonSocialUsuario = RazonSocialUsuario;
            inValue.Body.CorreoUsuario = CorreoUsuario;
            inValue.Body.TipoUsuario = TipoUsuario;
            Dashboard.WsEnrola.AgregarUsuarioResponse retVal = ((Dashboard.WsEnrola.Service1Soap)(this)).AgregarUsuario(inValue);
            return retVal.Body.AgregarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.AgregarUsuarioResponse> Dashboard.WsEnrola.Service1Soap.AgregarUsuarioAsync(Dashboard.WsEnrola.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WsEnrola.AgregarUsuarioResponse> AgregarUsuarioAsync(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, string ClaveUsuario, string RazonSocialUsuario, string CorreoUsuario, Dashboard.WsEnrola.TipoUsuario TipoUsuario) {
            Dashboard.WsEnrola.AgregarUsuarioRequest inValue = new Dashboard.WsEnrola.AgregarUsuarioRequest();
            inValue.Body = new Dashboard.WsEnrola.AgregarUsuarioRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.CuentaAdmin = CuentaAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.RazonSocialUsuario = RazonSocialUsuario;
            inValue.Body.CorreoUsuario = CorreoUsuario;
            inValue.Body.TipoUsuario = TipoUsuario;
            return ((Dashboard.WsEnrola.Service1Soap)(this)).AgregarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WsEnrola.AsignarTimbresResponse Dashboard.WsEnrola.Service1Soap.AsignarTimbres(Dashboard.WsEnrola.AsignarTimbresRequest request) {
            return base.Channel.AsignarTimbres(request);
        }
        
        public Dashboard.WsEnrola.WSEnrolaResponse AsignarTimbres(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            Dashboard.WsEnrola.AsignarTimbresRequest inValue = new Dashboard.WsEnrola.AsignarTimbresRequest();
            inValue.Body = new Dashboard.WsEnrola.AsignarTimbresRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.UsuarioAdmin = UsuarioAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.Timbres = Timbres;
            Dashboard.WsEnrola.AsignarTimbresResponse retVal = ((Dashboard.WsEnrola.Service1Soap)(this)).AsignarTimbres(inValue);
            return retVal.Body.AsignarTimbresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.AsignarTimbresResponse> Dashboard.WsEnrola.Service1Soap.AsignarTimbresAsync(Dashboard.WsEnrola.AsignarTimbresRequest request) {
            return base.Channel.AsignarTimbresAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WsEnrola.AsignarTimbresResponse> AsignarTimbresAsync(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            Dashboard.WsEnrola.AsignarTimbresRequest inValue = new Dashboard.WsEnrola.AsignarTimbresRequest();
            inValue.Body = new Dashboard.WsEnrola.AsignarTimbresRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.UsuarioAdmin = UsuarioAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.Timbres = Timbres;
            return ((Dashboard.WsEnrola.Service1Soap)(this)).AsignarTimbresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WsEnrola.AgregarTimbresResponse Dashboard.WsEnrola.Service1Soap.AgregarTimbres(Dashboard.WsEnrola.AgregarTimbresRequest request) {
            return base.Channel.AgregarTimbres(request);
        }
        
        public Dashboard.WsEnrola.WSEnrolaResponse AgregarTimbres(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            Dashboard.WsEnrola.AgregarTimbresRequest inValue = new Dashboard.WsEnrola.AgregarTimbresRequest();
            inValue.Body = new Dashboard.WsEnrola.AgregarTimbresRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.UsuarioAdmin = UsuarioAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.Timbres = Timbres;
            Dashboard.WsEnrola.AgregarTimbresResponse retVal = ((Dashboard.WsEnrola.Service1Soap)(this)).AgregarTimbres(inValue);
            return retVal.Body.AgregarTimbresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.AgregarTimbresResponse> Dashboard.WsEnrola.Service1Soap.AgregarTimbresAsync(Dashboard.WsEnrola.AgregarTimbresRequest request) {
            return base.Channel.AgregarTimbresAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WsEnrola.AgregarTimbresResponse> AgregarTimbresAsync(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            Dashboard.WsEnrola.AgregarTimbresRequest inValue = new Dashboard.WsEnrola.AgregarTimbresRequest();
            inValue.Body = new Dashboard.WsEnrola.AgregarTimbresRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.UsuarioAdmin = UsuarioAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.Timbres = Timbres;
            return ((Dashboard.WsEnrola.Service1Soap)(this)).AgregarTimbresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WsEnrola.QuitarTimbresResponse Dashboard.WsEnrola.Service1Soap.QuitarTimbres(Dashboard.WsEnrola.QuitarTimbresRequest request) {
            return base.Channel.QuitarTimbres(request);
        }
        
        public Dashboard.WsEnrola.WSEnrolaResponse QuitarTimbres(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            Dashboard.WsEnrola.QuitarTimbresRequest inValue = new Dashboard.WsEnrola.QuitarTimbresRequest();
            inValue.Body = new Dashboard.WsEnrola.QuitarTimbresRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.UsuarioAdmin = UsuarioAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.Timbres = Timbres;
            Dashboard.WsEnrola.QuitarTimbresResponse retVal = ((Dashboard.WsEnrola.Service1Soap)(this)).QuitarTimbres(inValue);
            return retVal.Body.QuitarTimbresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.QuitarTimbresResponse> Dashboard.WsEnrola.Service1Soap.QuitarTimbresAsync(Dashboard.WsEnrola.QuitarTimbresRequest request) {
            return base.Channel.QuitarTimbresAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WsEnrola.QuitarTimbresResponse> QuitarTimbresAsync(string RfcAdmin, string UsuarioAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, int Timbres) {
            Dashboard.WsEnrola.QuitarTimbresRequest inValue = new Dashboard.WsEnrola.QuitarTimbresRequest();
            inValue.Body = new Dashboard.WsEnrola.QuitarTimbresRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.UsuarioAdmin = UsuarioAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.Timbres = Timbres;
            return ((Dashboard.WsEnrola.Service1Soap)(this)).QuitarTimbresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WsEnrola.CambiarClaveResponse Dashboard.WsEnrola.Service1Soap.CambiarClave(Dashboard.WsEnrola.CambiarClaveRequest request) {
            return base.Channel.CambiarClave(request);
        }
        
        public Dashboard.WsEnrola.WSEnrolaResponse CambiarClave(string RfcUsuario, string CuentaUsuario, string ClaveActual, string ClaveNueva) {
            Dashboard.WsEnrola.CambiarClaveRequest inValue = new Dashboard.WsEnrola.CambiarClaveRequest();
            inValue.Body = new Dashboard.WsEnrola.CambiarClaveRequestBody();
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.ClaveActual = ClaveActual;
            inValue.Body.ClaveNueva = ClaveNueva;
            Dashboard.WsEnrola.CambiarClaveResponse retVal = ((Dashboard.WsEnrola.Service1Soap)(this)).CambiarClave(inValue);
            return retVal.Body.CambiarClaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.CambiarClaveResponse> Dashboard.WsEnrola.Service1Soap.CambiarClaveAsync(Dashboard.WsEnrola.CambiarClaveRequest request) {
            return base.Channel.CambiarClaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WsEnrola.CambiarClaveResponse> CambiarClaveAsync(string RfcUsuario, string CuentaUsuario, string ClaveActual, string ClaveNueva) {
            Dashboard.WsEnrola.CambiarClaveRequest inValue = new Dashboard.WsEnrola.CambiarClaveRequest();
            inValue.Body = new Dashboard.WsEnrola.CambiarClaveRequestBody();
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.ClaveActual = ClaveActual;
            inValue.Body.ClaveNueva = ClaveNueva;
            return ((Dashboard.WsEnrola.Service1Soap)(this)).CambiarClaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WsEnrola.InhabilitarUsuarioResponse Dashboard.WsEnrola.Service1Soap.InhabilitarUsuario(Dashboard.WsEnrola.InhabilitarUsuarioRequest request) {
            return base.Channel.InhabilitarUsuario(request);
        }
        
        public Dashboard.WsEnrola.WSEnrolaResponse InhabilitarUsuario(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario) {
            Dashboard.WsEnrola.InhabilitarUsuarioRequest inValue = new Dashboard.WsEnrola.InhabilitarUsuarioRequest();
            inValue.Body = new Dashboard.WsEnrola.InhabilitarUsuarioRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.CuentaAdmin = CuentaAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            Dashboard.WsEnrola.InhabilitarUsuarioResponse retVal = ((Dashboard.WsEnrola.Service1Soap)(this)).InhabilitarUsuario(inValue);
            return retVal.Body.InhabilitarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.InhabilitarUsuarioResponse> Dashboard.WsEnrola.Service1Soap.InhabilitarUsuarioAsync(Dashboard.WsEnrola.InhabilitarUsuarioRequest request) {
            return base.Channel.InhabilitarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WsEnrola.InhabilitarUsuarioResponse> InhabilitarUsuarioAsync(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario) {
            Dashboard.WsEnrola.InhabilitarUsuarioRequest inValue = new Dashboard.WsEnrola.InhabilitarUsuarioRequest();
            inValue.Body = new Dashboard.WsEnrola.InhabilitarUsuarioRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.CuentaAdmin = CuentaAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            return ((Dashboard.WsEnrola.Service1Soap)(this)).InhabilitarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WsEnrola.CrearUsuarioRVResponse Dashboard.WsEnrola.Service1Soap.CrearUsuarioRV(Dashboard.WsEnrola.CrearUsuarioRVRequest request) {
            return base.Channel.CrearUsuarioRV(request);
        }
        
        public Dashboard.WsEnrola.WSEnrolaResponse CrearUsuarioRV(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, string ClaveUsuario, string CorreoUsuario) {
            Dashboard.WsEnrola.CrearUsuarioRVRequest inValue = new Dashboard.WsEnrola.CrearUsuarioRVRequest();
            inValue.Body = new Dashboard.WsEnrola.CrearUsuarioRVRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.CuentaAdmin = CuentaAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CorreoUsuario = CorreoUsuario;
            Dashboard.WsEnrola.CrearUsuarioRVResponse retVal = ((Dashboard.WsEnrola.Service1Soap)(this)).CrearUsuarioRV(inValue);
            return retVal.Body.CrearUsuarioRVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WsEnrola.CrearUsuarioRVResponse> Dashboard.WsEnrola.Service1Soap.CrearUsuarioRVAsync(Dashboard.WsEnrola.CrearUsuarioRVRequest request) {
            return base.Channel.CrearUsuarioRVAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WsEnrola.CrearUsuarioRVResponse> CrearUsuarioRVAsync(string RfcAdmin, string CuentaAdmin, string ClaveAdmin, string RfcUsuario, string CuentaUsuario, string ClaveUsuario, string CorreoUsuario) {
            Dashboard.WsEnrola.CrearUsuarioRVRequest inValue = new Dashboard.WsEnrola.CrearUsuarioRVRequest();
            inValue.Body = new Dashboard.WsEnrola.CrearUsuarioRVRequestBody();
            inValue.Body.RfcAdmin = RfcAdmin;
            inValue.Body.CuentaAdmin = CuentaAdmin;
            inValue.Body.ClaveAdmin = ClaveAdmin;
            inValue.Body.RfcUsuario = RfcUsuario;
            inValue.Body.CuentaUsuario = CuentaUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CorreoUsuario = CorreoUsuario;
            return ((Dashboard.WsEnrola.Service1Soap)(this)).CrearUsuarioRVAsync(inValue);
        }
    }
}
